parameters:
    # Security
    ezsettings.default.security.token_interval_spec: PT1H
    ezsettings.default.user_change_password.templates.form: "EzPlatformUserBundle:change_password:index.html.twig"
    ezsettings.default.user_change_password.templates.success: "EzPlatformUserBundle:change_password:success.html.twig"
    ezsettings.default.user_forgot_password.templates.form: "EzPlatformUserBundle:forgot_password:index.html.twig"
    ezsettings.default.user_forgot_password_success.templates.form: "EzPlatformUserBundle:forgot_password:success.html.twig"
    ezsettings.default.user_forgot_password_login.templates.form: "EzPlatformUserBundle:forgot_password:with_login.html.twig"
    ezsettings.default.user_forgot_password.templates.mail: "EzPlatformUserBundle:forgot_password/mail:forgot_user_password.html.twig"
    ezsettings.default.user_reset_password.templates.form: "EzPlatformUserBundle:reset_password:index.html.twig"
    ezsettings.default.user_reset_password.templates.invalid_link: "EzPlatformUserBundle:reset_password:invalid_link.html.twig"
    ezsettings.default.user_reset_password.templates.success: "EzPlatformUserBundle:reset_password:success.html.twig"

    # Registration
    ezsettings.default.user_registration.group_id: 11
    ezsettings.default.user_registration.templates.form: "EzSystemsRepositoryFormsBundle:Content:content_edit.html.twig"
    ezsettings.default.user_registration.templates.confirmation: "EzPlatformUserBundle:User:register_confirmation.html.twig"
